-- First, remove the table if it exists
drop table if exists notes;

-- Create the table anew
create table notes (
  id INTEGER primary key generated by default as identity,
  modified TEXT NOT NULL,
  content TEXT NOT NULL,
  name  varchar(50),
  folderId INTEGER
);

-- Add Cascades for folder note relationship
ALTER TABLE notes ADD FOREIGN KEY (folderId)
REFERENCES folders(id) ON DELETE CASCADE;